### ISSUE TITLE
Optional build parameters

### ISSUE THREAD

**Issue by IanVS** [jpstevens/circleci#12]
The README mentions that this client does not support optional build parameters.  This would be super-useful for me, do you plan to add that support?  Do you expect it will be difficult to do?  I'd try it, but I've never worked in coffeescript before.

**Comment by IanVS** [comment]
Actually, it seems this was added by https://github.com/jpstevens/circleci/commit/5c25e2de833cf60849bb79aada985eec1294b562.  So I guess the README just needs to be updated?

**Comment by jpstevens** [comment]
@IanVS yep, the README hasn't been updated yet. If you want to update it I'd be happy to merge your PR 👍

**Comment by elliottcrush** [comment]
I've got a branch prepped and ready to update the docs as this caught me out today. Happy to push up if you want.

**Comment by jpstevens** [comment]
@elliottcrush Great, submit a PR and I'll merge + release

**Comment by elliottcrush** [comment]
Permission denied when pushing :(

**Comment by elliottcrush** [comment]
Would you be able to provide me with access to push please @jpstevens

**Comment by IanVS** [comment]
You shouldn't need push access, @elliottcrush.  The typical approach is to fork the repo, create a branch on your fork, and then submit a pull request from there.

**Comment by elliottcrush** [comment]
This is now in PR @IanVS

**Comment by jpstevens** [comment]
Thanks @IanVS @elliottcrush for you help with this. Feature has been merged and published to npm (v0.3.3)

**Comment by drazisil** [comment]
Does that mean this issue can be closed?
