### ISSUE TITLE
getBranchBuilds not working

### ISSUE THREAD

**Issue by mhle** [jpstevens/circleci#5]
is this implemented?

**Comment by imsky** [comment]
it seems to be not published through npm, but is available in source

**Comment by imsky** [comment]
I republished the package here under `circleci2`: https://www.npmjs.com/package/circleci2

**Comment by jpstevens** [comment]
Hey guys, have (finally) gotten around to re-publishing, along with some other new features such as parameterised builds, etc.

Check out v0.3.0 :+1:

**Comment by imsky** [comment]
good stuff
