### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by mCzolko** [jpstevens/circleci#8]
The index script should be located here:
https://github.com/jpstevens/circleci/blob/master/package.json#L5

but in the NPM ignore file this file is ignored.

Jack, please, can you do a fresh installation of this lib to see what's happening?

When I install this lib as a dependency all I can find in node_modules/circleci is one folder (node_modules) and 3 files: circle.yml, package.json and README.md you somehow ignored the necessary files :D 

Cheers

**Comment by jpstevens** [comment]
Just saw this. Will action later today.

**Comment by RealOrangeOne** [comment]
:+1: Please fix, Looks like the `dist/` directory wasn't pushed up to npm on deployment of `0.3.0`.

**Comment by jpstevens** [comment]
Thanks @RealOrangeOne 
Have added a `prepublish` command to the `package.json` to avoid this happening in future. Not sure why it wasn't already like that :+1:

**Comment by jpstevens** [comment]
@mCzolko fixed

**Comment by mCzolko** [comment]
Thank you so much! :)
